entree_project/entree/urls.py
from django.conf.urls import url
from entree import views

app_name = 'entree'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^register/$', views.register, name='register'),
    url(r'^user/profile/$', views.profile, name='profile'),
    url(r'^about/$', views.about, name='about'),
    url(r'posts/$', views.posts, name='posts'),
    url(r'posts/(?P<photo_id>[0-9]+)/$', views.post_detail, name='post_detail'),
]

entree_project/entree_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView
from entree import views

handler400 = 'entree.views.bad_request'
handler403 = 'entree.views.permission_denied'
handler404 = 'entree.views.page_not_found'
handler500 = 'entree.views.server_error'

urlpatterns = [
    url(r'^$', RedirectView.as_view(url='entree/')),
    url(r'^entree/', include('entree.urls', namespace='entree')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += [
        url(r'^400/$', views.bad_request),
        url(r'^403/$', views.permission_denied),
        url(r'^404/$', views.page_not_found),
        url(r'^500/$', views.server_error),
    ]

entree_project/entree/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


class UserProfile(models.Model):

    """
    Extends the default Django User model. The default user includes:
    - username
    - first_name
    - last_name
    - email
    - password
    - groups
    - is_staff
    - is_active
    - is_superuser
    - last_login
    - date_joined
    """

    user = models.OneToOneField(
        User, # refers to Django User implementation
        on_delete=models.CASCADE,
        blank=False
    )


class FlickrClient(models.Model):

    """
    Stores our flickr API key securely on the server.
    """

    api_key = models.CharField(
        max_length=32,
        blank=False
    )
    secret_key = models.CharField(
        max_length=16,
        blank=False
    )


class FlickrPost(models.Model):

    """
    For caching flickr post information on the server between searches.

    All fields but 'latitude' and 'longitude' are populated when the post is first fetched from the server.
    The latitude and longitude fields are then populated by a separate API request the first time the post
    is viewed in detail. This dramatically improves the performance of the initial post list.
    """

    id = models.BigIntegerField(  # we use this for pk lookup of posts
        primary_key=True,
        blank=False
    )
    secret = models.CharField(
        max_length=32,
        blank=False
    )
    farm = models.PositiveSmallIntegerField(  # supports values up to 32767, maybe more (database dependent)
        blank=False
    )
    server = models.PositiveSmallIntegerField(
        blank=False
    )
    owner = models.CharField(
        max_length=32,
        blank=False
    )
    title = models.CharField(
        max_length=256,
        blank=True
    )
    image_url = models.CharField(  # we generate this during pre-processing on the server
        max_length=512,
        blank=False
    )
    search_term = models.CharField(  # the associated search term that was used to fetch this post
        max_length=64,
        blank=False
    )
    date_fetched = models.DateTimeField(
        default=timezone.now,
        blank=False
    )
    latitude = models.DecimalField(  # between -90 and 90 degrees
        max_digits=9,
        decimal_places=6,
        null=True,
        blank=True
    )
    longitude = models.DecimalField(  # between -180 and 180 degrees
        max_digits=9,
        decimal_places=6,
        null=True,
        blank=True
    )
    description = models.TextField(
        blank=True
    )
    page = models.PositiveIntegerField(
        default=1,
        blank=False
    )


class YelpClient(models.Model):

    """
    Stores our Yelp API keys securely on the server.
    """
    consumer_key = models.CharField(
        max_length=32,
        blank=False
    )
    consumer_secret = models.CharField(
        max_length=32,
        blank=False
    )
    token = models.CharField(
        max_length=32,
        blank=False
    )
    token_secret = models.CharField(
        max_length=32,
        blank=False
    )

entree_project/entree/forms.py
from django import forms
from django.contrib.auth.models import User
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout
from passwords.fields import PasswordField  # django-password


class RegisterForm(forms.Form):

    username = forms.CharField(
        label="Username",
        max_length=30,
        min_length=3,
        required=True
    )
    password = PasswordField(
        label="Password"
    )
    first_name = forms.CharField(
        label="First name",
        max_length=30,
        required=False
    )
    last_name = forms.CharField(
        label="Last name",
        max_length=30,
        required=False
    )
    email = forms.EmailField(
        label="Email",
        required=False
    )

    def clean(self):
        cleaned_data = super(RegisterForm, self).clean()
        username = cleaned_data.get('username')

        if User.objects.filter(username=username).count():
            self.add_error(
                'username',
                "This username is already in use."
            )

        return cleaned_data

    def __init__(self, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)

        # Crispy Forms Helper
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.form_id = "register-form"

        # customize the layout
        self.helper.layout = Layout(
            'username',
            'password',
            'first_name',
            'last_name',
            'email'
        )


class EditUserForm(forms.Form):

    first_name = forms.CharField(
        label="First name:",
        max_length=30,
        required=False
    )
    last_name = forms.CharField(
        label="Last name:",
        max_length=30,
        required=False
    )
    email = forms.EmailField(
        label="Email:",
        required=False
    )

    def __init__(self, *args, **kwargs):
        super(EditUserForm, self).__init__(*args, **kwargs)

        # Crispy Forms Helper
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.form_id = "user-form"

        # customize the layout
        self.helper.layout = Layout(
            'first_name',
            'last_name',
            'email'
        )

entree_project/entree/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from entree.models import *
from entree.forms import RegisterForm, EditUserForm
from entree_project.settings import APP_VERSION, NUM_RESULTS
from datetime import timedelta
from yelp.client import Client
from yelp.oauth1_authenticator import Oauth1Authenticator
import requests
import simplejson
import html.parser


FLICKR_REST_ROOT_URL = 'https://api.flickr.com/services/rest/?method='


# Global site context
context_dict = {
    'version': 'v' + APP_VERSION
}

def bad_request(request):
    context_dict['status_code'] = 400
    context_dict['status_name'] = 'Bad Request'
    context_dict['status_description'] = "Sorry, your request could not be understood by the server."
    response = render(request, 'error.html', context_dict)
    response.status_code = 400
    return response


def permission_denied(request):
    context_dict['status_code'] = 403
    context_dict['status_name'] = 'Permission Denied'
    context_dict['status_description'] = "Sorry, you do not have permission to access this page."
    response = render(request, 'error.html', context_dict)
    response.status_code = 403
    return response


def page_not_found(request):
    context_dict['status_code'] = 404
    context_dict['status_name'] = 'Page Not Found'
    context_dict['status_description'] = "Sorry, the page you were trying to view does not exist."
    response = render(request, 'error.html', context_dict)
    response.status_code = 404
    return response


def server_error(request):
    context_dict['status_code'] = 500
    context_dict['status_name'] = 'Server Error'
    context_dict['status_description'] = "Sorry, an error occured while processing your request."
    response = render(request, 'error.html', context_dict)
    response.status_code = 500
    return response


def login(request):

    login_failed = False
    new_login = True

    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)

        if user is not None:
            if user.is_active:
                auth_login(request, user)
                login_failed = False
                return redirect('/entree/', context_dict)

        login_failed = True
        new_login = False

    else:

        # user redirected from registration page
        if 'registered' in request.GET:
            new_login = False

    context_dict['login_failed'] = login_failed
    context_dict['new_login'] = new_login
    return render(request, 'entree/login.html', context_dict)


@login_required
def logout(request):
    auth_logout(request)
    return redirect('/entree/login/', context_dict)


def register(request):

    if request.method == 'POST':
        register_form = RegisterForm(request.POST)

        if register_form.is_valid():
            data = register_form.cleaned_data

            user = User(
                username=data['username'],
                first_name=data['first_name'],
                last_name=data['last_name'],
                email=data['email']
            )
            user.set_password(data['password'])
            user.save()

            profile = UserProfile(
                user=user
            )
            profile.save()

            context_dict['new_login'] = False
            return redirect('/entree/login/?registered=true', context_dict)

    else:
        register_form = RegisterForm()

    context_dict['register_form'] = register_form
    return render(request, 'entree/register.html', context_dict)


def about(request):
    return render(request, 'entree/about.html', context_dict)


@login_required
def profile(request):

    user = request.user

    if request.method == 'POST':
        user_form = EditUserForm(request.POST)

        if user_form.is_valid():
            data = user_form.cleaned_data

            user.first_name = data['first_name']
            user.last_name = data['last_name']
            user.email = data['email']
            user.save()

            return redirect('/entree/user/profile/', context_dict)
    else:

        if 'edit' in request.GET:
            editing = True

            user_form = EditUserForm(
                initial={
                    'first_name': user.first_name,
                    'last_name': user.last_name,
                    'email': user.email
                }
            )

        else:
            editing = False
            user_form = None

    context_dict['editing'] = editing
    context_dict['user_form'] = user_form
    return render(request, 'entree/profile.html', context_dict)


@login_required
def index(request):
    if 'invalid_search' in request.GET:
        context_dict['search_error'] = True
    else:
        context_dict['search_error'] = False
    return render(request, 'entree/index.html', context_dict)


@login_required
def posts(request):

    if 'city' not in request.GET:
        return redirect('/entree/' + '?invalid_search=true', context_dict)

    city = request.GET['city'].lower()

    if city == '':
        return redirect('/entree/' + '?invalid_search=true', context_dict)

    if 'page' in request.GET:
        page = int(request.GET['page'])

        if not page >= 1:
            page = 1
    else:
        page = 1  # start at the first page

    context_dict['city'] = city.title()
    context_dict['next_page'] = page + 1

    posts = __search_flickr_posts(city, page)

    for post in posts:
        if not FlickrPost.objects.filter(id=post['id']).count():
            # post not already in database
            flickrpost = FlickrPost(
                id=post['id'],
                secret=post['secret'],
                farm=post['farm'],
                server=post['server'],
                owner=post['owner'],
                title=post['title'],
                image_url=post['url'],
                search_term=city,
                page=page
            )
            flickrpost.save()

    context_dict['post_list'] = FlickrPost.objects.filter(search_term=city).filter(page=page).order_by('-date_fetched')
    return render(request, 'entree/posts.html', context_dict)


@login_required
def post_detail(request, photo_id):
    try:
        # get Flickr Post details
        post = FlickrPost.objects.get(pk=photo_id)
        context_dict['valid_post'] = True

        h = html.parser.HTMLParser()

        if not post.latitude or not post.longitude:
            photo = __get_flickr_post_info(photo_id)
            post.latitude = float(photo['location']['latitude'])
            post.longitude = float(photo['location']['longitude'])
            post.description = h.unescape(photo['description']['_content'])
            post.save()

        context_dict['post'] = post

        # get Yelp reviews for that location
        yelp = YelpClient.objects.get(pk=1)
        auth = Oauth1Authenticator(
            consumer_key=yelp.consumer_key,
            consumer_secret=yelp.consumer_secret,
            token=yelp.token,
            token_secret=yelp.token_secret
        )
        client = Client(auth)

        # get location that most closely matches the geolocation
        best_business = None
        alt_businesses = list()
        yelp_api_error = False

        try:
            response = client.search_by_coordinates(post.latitude, post.longitude)

            if response.businesses:
                best_business = response.businesses[0]

                if len(response.businesses) > 5:
                    alt_businesses = response.businesses[1:6]

                elif len(response.businesses) > 1:
                    alt_businesses = response.businesses[1:]

        except:
            yelp_api_error = True

        context_dict['yelp_api_error'] = yelp_api_error
        context_dict['best_business'] = best_business
        context_dict['alt_businesses'] = alt_businesses

    except FlickrPost.DoesNotExist:
        context_dict['valid_post'] = False

    return render(request, 'entree/post_detail.html', context_dict)


def __get_flickr_post_info(photo_id):
    method = 'flickr.photos.getInfo'
    params = {
        'photo_id': photo_id
    }
    url = __build_flickr_rest_url(method, params)

    response = simplejson.loads(__flickr_json_fix(requests.get(url).text))
    return response['photo']


def __search_flickr_posts(city, page):
    method = 'flickr.photos.search'
    params = {
        'tags': city + ',food',
        'tag_mode': 'all',              # only return photos that include all of the tags
        'privacy_filter': 1,            # 1 = public
        'has_geo': 1,                   # only return images that have geolocation information
        'per_page': NUM_RESULTS,
        'page': page
    }
    url = __build_flickr_rest_url(method, params)

    response = simplejson.loads(__flickr_json_fix(requests.get(url).text))
    photos = response['photos']['photo']
    image_url = 'https://farm{0}.staticflickr.com/{1}/{2}_{3}.jpg'
    post_list = list()

    for i in range(len(photos)):
        post = photos[i]
        post['url'] = image_url.format(post['farm'], post['server'], post['id'], post['secret'])
        post_list.append(post)

    return post_list


def __build_flickr_rest_url(method, params):
    flickr = FlickrClient.objects.get(pk=1)
    url = FLICKR_REST_ROOT_URL
    url += method
    params['api_key'] = flickr.api_key
    params['format'] = 'json'

    for key in params.keys():
        url += '&' + str(key) + '=' + str(params[key])

    return url


def __flickr_json_fix(json_string):
    # Removes the "jsonFlickrApi( ... )" wrapper around the response's JSON
    return json_string.replace('jsonFlickrApi(', '').replace(')', '')

entree_project/entree/templates/entree/about.html
{% extends 'entree/base.html' %}

{% load staticfiles i18n %}

{% block title %}{{block.super}} | About{% endblock title %}

{% block page_content %}
    <div class="row">
        <div class="col-lg-12">
            <h2 class="page-header">About Entrée</h2>
        </div>
        <div class="col-lg-12">
            <h5>"Tinder for food."</h5>
            <p>
                Entree was developed as a proof of concept by students at Boston University.
                <br/><br/>
                Carlton Duffett<br/>
                George Gelinas<br/>
                Nick Morrison<br/>
                Lambert Shao<br/>
                <br/>
                CS411 Spring 2016
            </p>
        </div>
    </div>
{% endblock page_content %}

entree_project/entree/templates/entree/base.html
{% load staticfiles i18n %}

<!DOCTYPE html>
<html lang="en">

<head>
    {% block meta_tags %}
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">
    {% endblock meta_tags %}

    <title>
        {% block title %}Entree{% endblock title %}
    </title>

    {% block stylesheets %}
        <!-- Bootstrap Core CSS -->
        <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">

        <!-- Bootswatch Free Theme -->
        <link href="//cdnjs.cloudflare.com/ajax/libs/bootswatch/3.3.6/paper/bootstrap.min.css" rel="stylesheet">

        <!-- Custom CSS -->
        <link href="{% static 'entree/css/base.css' %}" rel="stylesheet">
    {% endblock stylesheets %}

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="//oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="//oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    {% block extra_head %}{% endblock extra_head %}
</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'entree:index' %}">
                    {% block brand %}Entrée {{version}}{% endblock brand %}
                </a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">

                    {% if user.is_authenticated %}
                        <li>
                            <a href="{% url 'entree:index' %}">Search</a>
                        </li>
                        <li>
                            <a href="{% url 'entree:profile' %}">Profile</a>
                        </li>
                        {% if user.is_superuser %}
                            <li>
                                <a href="{% url 'admin:index' %}">Admin Site</a>
                            </li>
                        {% endif %}
                        <li>
                            <a href="{% url 'entree:logout' %}">Logout</a>
                        </li>
                    {% endif %}

                    <li>
                        <a href="{% url 'entree:about' %}">About</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Content -->
    <div class="container">
        {% block page_content %}
        {% endblock page_content %}
        <hr>

        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; Entree 2016</p>
                </div>
            </div>
        </footer>

    </div>
    <!-- /.container -->
    {% block javascript %}
        <!-- jQuery -->
        <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>

        <!-- Bootstrap Core JavaScript -->
        <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    {% endblock javascript %}
</body>

</html>

entree_project/entree/templates/entree/index.html
{% extends 'entree/base.html' %}

{% load staticfiles i18n %}

{% block title %}{{block.super}} | Search{% endblock title %}

{% block stylesheets %}
    {{block.super}}
    <!-- Custom CSS -->
    <link href="{% static 'entree/css/index.css' %}" rel="stylesheet">
{% endblock stylesheets %}

{% block page_content %}
    <div class="row">

        <h1 class="text-center">Welcome, {% if user.first_name %}{{user.first_name}}{% else %}{{user.username}}{% endif %}</h1>

        <div class="col-xs-10 col-xs-offset-1 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3 col-lg-6 col-lg-offset-3">
            <div class="panel panel-default panel-search">
                <div class="panel-heading">
                    <h3 class="panel-title">Search for Food by City</h3>
                </div>
                <div class="panel-body">
                    <form role="form" method="get" action="{% url 'entree:posts' %}" novalidate>
                        <fieldset>
                            <div class="form-group">
                                <input class="form-control" placeholder="city" name="city" type="text" autofocus maxlength="64">
                                {% if search_error %}
                                    <p class="error-msg">Invalid search term</p>
                                {% endif %}
                            </div>
                            <button type="submit" class="btn btn-primary">Search</button>
                        </fieldset>
                    </form>
                </div>
            </div><!-- /.panel -->
        </div><!-- /.col-md-4 -->
    </div><!-- /.row -->
{% endblock page_content %}

entree_project/entree/templates/entree/login.html
{% extends 'entree/base.html' %}

{% load staticfiles %}

{% block stylesheets %}
    {{block.super}}
    <!-- Custom CSS -->
    <link href="{% static 'entree/css/login.css' %}" rel="stylesheet">
{% endblock stylesheets %}

{% block page_content %}
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <div class="login-panel panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Please Sign In</h3>
                </div>
                <div class="panel-body">
                    {% if login_failed %}
                        <div class="alert alert-danger"><p>Invalid username or password</p></div>
                    {% endif %}
                    <form role="form" method="post" action="{% url 'entree:login' %}">
                        {% csrf_token %}
                        <fieldset>
                            <div class="form-group">
                                <input class="form-control" placeholder="Username" name="username" type="text" autofocus>
                            </div>
                            <div class="form-group">
                                <input class="form-control" placeholder="Password" name="password" type="password" value="">
                            </div>
                            <!--
                            <div class="checkbox">
                                <label>
                                    <input name="remember" type="checkbox" value="Remember Me">Remember Me
                                </label>
                            </div>
                            -->
                            <!-- Change this to a button or input when using this as a form -->
                            <button type="submit" class="btn btn-primary btn-block">Login</button>
                        </fieldset>
                    </form>
                    {% if new_login %}
                        <div class="or-label text-center">OR</div>
                        <a href="{% url 'entree:register' %}" class="btn btn-default btn-block">Sign Up</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock page_content %}

entree_project/entree/templates/entree/post_detail.html
{% extends 'entree/base.html' %}

{% load staticfiles i18n %}

{% block title %}{{block.super}} | Post Detail{% endblock title %}

{% block stylesheets %}
    {{block.super}}
    <!-- Custom CSS -->
    <link href="{% static 'entree/css/post_detail.css' %}" rel="stylesheet">

    <!-- Mapbox CSS -->
    <link href='https://api.tiles.mapbox.com/mapbox-gl-js/v0.17.0/mapbox-gl.css' rel='stylesheet'/>
{% endblock stylesheets %}

{% block page_content %}
    <div class="row">

        <!-- Flickr Post Detail panel -->
        <div class="col-xs-12 col-xs-offset-0 col-sm-6 col-sm-offset-0 col-md-6 col-md-offset-0 col-lg-4 col-lg-offset-0">
            <div class="post-panel panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Flickr Post</h3>
                </div>
                <div class="panel-body">
                    <img src="{{post.image_url}}" width="100%">
                    {% if post.description %}
                        <div class="post-description well">
                            <p>{{post.description}}</p>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>

        <!-- Map and Closest Matching Business panel -->
        <div class="col-xs-12 col-xs-offset-0 col-sm-6 col-sm-offset-0 col-md-6 col-md-offset-0 col-lg-4 col-lg-offset-0">
            <div class="post-panel panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Closest Matching Business</h3>
                </div>
                <div class="panel-body">

                    <span id="lat" hidden>{{post.latitude}}</span>
                    <span id="long" hidden>{{post.longitude}}</span>

                    <div id='map'></div>

                    {% if yelp_api_error %}
                        <div class="alert alert-warning">No Yelp data found for this location.</div>
                    {% else %}
                        <h3 id="business_name">{{best_business.name}}</h3><br/>
                        <address>
                            {% for el in best_business.location.display_address %}
                                {{el}}<br/>
                            {% endfor %}
                        </address>

                        <dl>
                            <dt>Rating</dt>
                            <dd><img src="{{best_business.rating_img_url}}"><br></dd>
                            <dt>Reviews</dt>
                            <dd><a href="{{best_business.url}}" target="_blank">Go to Yelp Reviews</a></dd>
                        </dl>
                    {% endif %}
                </div>
            </div>
        </div>

        <!-- Other Nearby Businesses panel -->
        <div class="col-xs-12 col-xs-offset-0 col-sm-6 col-sm-offset-0 col-md-6 col-md-offset-0 col-lg-4 col-lg-offset-0">
            <div class="post-panel panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Nearby Businesses</h3>
                </div>
                <div class="panel-body">
                    {% if yelp_api_error %}
                        <div class="alert alert-warning">No Yelp data found for this location.</div>
                    {% else %}
                        <div class="list-group">
                            {% for bus in alt_businesses %}
                                <a class="list-group-item" href="{{bus.url}}">
                                    <img src="{{bus.image_url}}" width="100px" height="100px" class="pull-right">
                                    <h5>{{bus.name}}</h5>
                                    <dl>
                                        <dt>Rating</dt>
                                        <dd><img src="{{bus.rating_img_url}}"></dd>
                                    </dl>
                                </a>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div><!-- /.row -->
{% endblock page_content %}

{% block javascript %}
    {{block.super}}
    <!-- Mapbox JavaScript -->
    <script src='https://api.tiles.mapbox.com/mapbox-gl-js/v0.17.0/mapbox-gl.js'></script>
    <script src="{% static 'entree/js/mapbox.js' %}"></script>
{% endblock javascript %}

entree_project/entree/templates/entree/posts.html
{% extends 'entree/base.html' %}

{% load staticfiles i18n %}

{% block title %}{{block.super}} | Posts{% endblock title %}

{% block stylesheets %}
    {{block.super}}
    <!-- Custom CSS -->
    <link href="{% static 'entree/css/posts.css' %}" rel="stylesheet">
{% endblock stylesheets %}

{% block page_content %}
    {% if post_list %}
        <div class="row">
            <div class="col-lg-12">
                <h2 class="page-header">Flickr Posts for {{city}}</h2>
            </div>

            {% for post in post_list %}
                <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12 thumb">
                    <a class="thumbnail" href="{% url 'entree:post_detail' post.id %}">
                        <img class="img-responsive" src="{{post.image_url}}" alt="" width="400" height="300">
                    </a>
                </div>
            {% endfor %}
        </div> <!-- /.row -->
        <div class="row">
             <hr/>
            <div class="col-lg-12 text-center">
                <a class="btn btn-default btn-load" href="./?city={{city}}&page={{next_page}}">Load More</a>
            </div>
        </div>
    {% else %}
        <div class="row">
            <div class="col-lg-12 text-center">
                <h3 class="no-posts-alert">No posts found =(</h3>
            </div>
        </div>
    {% endif %}
{% endblock page_content %}